# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('event_date', models.DateField()),
                ('tigers', models.IntegerField()),
                ('panthers', models.IntegerField()),
                ('lions', models.IntegerField()),
                ('jaguars', models.IntegerField()),
            ],
        ),
    ]
