# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school', '0002_auto_20170408_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='contenttypes.ContentType'),
        ),
    ]
