# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_event_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='event',
            name='students',
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.CharField(default='lol', max_length=1024),
        ),
    ]
