# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20170408_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='students',
        ),
    ]
